### ISSUE TITLE
Publishing different OS

### ISSUE THREAD

**Issue by voliveirajr** [raydac/mvn-golang#79]
I would like to ask for a help and if possible to add to the examples.
My application build 3 artefacts (win, osx, lin) using 3 different executions as the example in the wiki.
Trying to deploy it (mvn deploy) it deploys just a zip file with the go dependencies and the pom.xml.
How could I configure it to push the 3 versions under the same snapshot?
Thanks

**Comment by raydac** [comment]
Hello
I not very understand what do you want to get as "publishing different OS"
do you mean publishing of built artifacts in maven  repository? if yes then it sounds a bit strange because maven repository usually contains parts and modules to build code, but it is possible with [maven install plugin](https://maven.apache.org/plugins/maven-install-plugin/install-file-mojo.html), you can public generated executable files in repository and mark them through classifier
